almonwatch v1.0 beta 3
(1) blacklist error
(2) read absolute path for symlinked applications
(3) read executable with plutil instead of defaults to avoid ASCII mayhem with non-English strings

diff --git a/almonwatch b/almonwatch
--- a/almonwatch
+++ b/almonwatch
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # almonwatch
-# version 1.0 beta 2
+# version 1.0 beta 3
 
 # set -x
 # PS4=':$LINENO+'
@@ -28,7 +28,7 @@ if [[ $1 == "blacklist" ]] ; then
 		sqlite3 "$dbloc" "delete from ALM where path=\"$@\";" 2>/dev/null && echo "Success: blacklisted $2" || echo "Error blacklisting $2" >&2
 	elif [[ $1 == "id" ]] ; then
 		shift
-		sqlite3 "$dbloc" "delete from ALM where cfbid=\"$2\";" 2>/dev/null && echo "Success: blacklisted $2" || echo "Error blacklisting $2" >&2
+		sqlite3 "$dbloc" "delete from ALM where cfbid=\"$1\";" 2>/dev/null && echo "Success: blacklisted $2" || echo "Error blacklisting $2" >&2
 	elif [[ $1 == "name" ]] ; then
 		shift
 		sqlite3 "$dbloc" "delete from ALM where name=\"$@\";" 2>/dev/null && echo "Success: blacklisted $@" || echo "Error blacklisting $@" >&2
@@ -403,11 +403,13 @@ _almonwatch () {
 			# parse input
 			pid=$(echo "$notification" | awk -F":::" '{print $2}')
 			filepath=$(echo "$notification" | awk -F":::" '{print $3}')
+			[[ -h "$filepath" ]] && filepath=$(perl -MCwd -e 'print Cwd::abs_path shift' "$filepath")
 			appname=$(echo "$notification" | awk -F":::" '{print $5}')
 			bundleid=$(echo "$notification" | awk -F":::" '{print $4}')
+			plistloc="$filepath/Contents/Info.plist"
 
 			# determine executable
-			executable=$(defaults read "$filepath/Contents/Info.plist" CFBundleExecutable)
+			executable=$(plutil -p "$plistloc" | awk -F\" '/CFBundleExecutable/{print $4}')
 			exepath="$filepath/Contents/MacOS/$executable"
 
 			# initial log
