almonwatch 1.0 beta 4
(1) true CLI "blacklist" functionality
(2) previous "blacklist" is now called "remove"
(3) add remove & blacklist info

diff --git a/almonwatch b/almonwatch
--- a/almonwatch
+++ b/almonwatch
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # almonwatch
-# version 1.0 beta 3 rev 2
+# version 1.0 beta 4
 
 # set -x
 # PS4=':$LINENO+'
@@ -11,29 +11,91 @@ export PATH=$PATH:/usr/local/bin
 
 if [[ $(id -u) != 0 ]] ; then
 	echo "Error: $0 needs to be run as root!" >&2
-	exit
+	exit 1
 fi
 
 supportdir="/Library/Application Support/ALM"
 dbloc="$supportdir/alm.db"
 
-if [[ $1 == "blacklist" ]] ; then
+if [[ $1 == "remove" ]] || [[ $1 == "blacklist" ]] ; then
 	if ! [[ -f "$dbloc" ]] ; then
 		echo "Error: database does not exist!" >&2
 		exit
 	fi
-	shift
-	if [[ $1 == "path" ]] ; then
-		shift
-		sqlite3 "$dbloc" "delete from ALM where path=\"$@\";" 2>/dev/null && echo "Success: blacklisted $2" || echo "Error blacklisting $2" >&2
-	elif [[ $1 == "id" ]] ; then
-		shift
-		sqlite3 "$dbloc" "delete from ALM where cfbid=\"$1\";" 2>/dev/null && echo "Success: blacklisted $2" || echo "Error blacklisting $2" >&2
-	elif [[ $1 == "name" ]] ; then
-		shift
-		sqlite3 "$dbloc" "delete from ALM where name=\"$@\";" 2>/dev/null && echo "Success: blacklisted $@" || echo "Error blacklisting $@" >&2
-	else
+	if [[ $2 != "path" ]] && [[ $2 != "name" ]] && [[ $2 != "id" ]] ; then
 		echo "Error: wrong option - use 'path', 'name', or 'id'" >&2
+	fi
+	if [[ $1 == "remove" ]] ; then
+		shift
+		if [[ $1 == "path" ]] ; then
+			shift
+			echo "Removing: $@"
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where path = \"$@\");" 2>/dev/null)
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "delete from ALM where path=\"$@\";" 2>/dev/null
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where path = \"$@\");" 2>/dev/null)
+			[[ $oldentry == "0" ]] && echo "Success" || echo "Error!" >&2
+		elif [[ $1 == "name" ]] ; then
+			shift
+			echo "Removing: $@"
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where name=\"$@\");" 2>/dev/null)
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "delete from ALM where name=\"$@\";" 2>/dev/null
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where name=\"$@\");" 2>/dev/null)
+			[[ $oldentry == "0" ]] && echo "Success" || echo "Error!" >&2
+		elif [[ $1 == "id" ]] ; then
+			shift
+			echo "Removing: $1"
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where cfbid = \"$1\");" 2>/dev/null)
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "delete from ALM where cfbid=\"$1\";" 2>/dev/null
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where cfbid = \"$1\");" 2>/dev/null)
+			[[ $oldentry == "0" ]] && echo "Success" || echo "Error!" >&2
+		fi
+	elif [[ $1 == "blacklist" ]] ; then
+		shift
+		if [[ $1 == "path" ]] ; then
+			shift
+			echo "Blacklisting: $@"
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where path = \"$@\");" 2>/dev/null)
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "update ALM set whitelist = \"X\" where path=\"$@\";" 2>/dev/null
+			blstatus=$(sqlite3 "$dbloc" "select whitelist from ALM where path=\"$@\";" 2>/dev/null)
+			[[ $blstatus == "X" ]] && echo "Success" || echo "Error!" >&2
+		elif [[ $1 == "name" ]] ; then
+			shift
+			echo "Blacklisting: $@"
+			oldentry=$(sqlite3 "$dbloc" "select exists(select * from ALM where name=\"$@\");" 2>/dev/null)
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "update ALM set whitelist = \"X\" where name=\"$@\";" 2>/dev/null
+			blstatus=$(sqlite3 "$dbloc" "select whitelist from ALM where name=\"$@\";" 2>/dev/null)
+			[[ $blstatus == "X" ]] && echo "Success" || echo "Error!" >&2
+		elif [[ $1 == "id" ]] ; then
+			shift
+			echo "Blacklisting: $1"
+			if [[ $oldentry == "0" ]] ; then
+				echo "Error: no record found!"
+				exit
+			fi
+			sqlite3 "$dbloc" "update ALM set whitelist = \"X\" where cfbid=\"$1\";" 2>/dev/null
+			blstatus=$(sqlite3 "$dbloc" "select whitelist from ALM where cfbid=\"$1\";" 2>/dev/null)
+			[[ $blstatus == "X" ]] && echo "Success" || echo "Error!" >&2
+		fi
 	fi
 	exit
 fi
@@ -385,13 +447,13 @@ _almonwatch () {
 
 		if [[ $notification == "Listening..." ]] ; then
 			echo "almon is running..."
-			_beep
+			afplay "/System/Library/Components/CoreAudio.component/Contents/SharedSupport/SystemSounds/system/payment_success.aif" &
 			_notify "🔎 ALM has started…"
 			continue
 
 		elif [[ $notification == "Stopping..." ]] ; then
 			echo "almon has exited."
-			_beep
+			_beep &
 			_notify "⁉️ ALM has exited!" "Something went wrong…"
 			break
 
@@ -431,6 +493,13 @@ _almonwatch () {
 				echo "$appname: no database entry found!"
 			else
 				echo "$appname: found database entry"
+				if [[ $wlstatus == "X" ]] ; then
+					echo "$appname is blacklisted: aborting launch..."
+					_beep &
+					_notify "❌ Blacklisted! Aborting launch…" "$appname"
+					osascript -e 'tell application "$appname" to quit' && { sleep 3 ; kill -s KILL $pid 2>/dev/null ; }
+					continue
+				fi
 				dbentry=true
 				if [[ $wlstatus == 1 ]] ; then
 					whitelisted=true
@@ -546,7 +615,6 @@ _almonwatch () {
 						wlstatus="1"
 					fi
 					sqlite3 "$dbloc" "update ALM set path = \"$filepath\", name = \"$appname\", teamid = \"$team\", anchor = \"$anchor\", skid = \"$skid\", certid = \"$certid\", hash = \"$exehash\", whitelist = \"1\", spctl = \"$gk_issue\", certsec = \"$certsec\" where cfbid = \"$bundleid\";"
-					# sqlite3 "$dbloc" "update ALM set (path,name,teamid,anchor,skid,certid,hash,whitelist,spctl,certsec) values (\"$filepath\",\"$appname\",\"$team\",\"$anchor\",\"$skid\",\"$certid\",\"$exehash\",\"1\",\"$gk_issue\",\"$certsec\") where cfbid = \"$bundleid\";"
 				fi
 			else
 				if $errors ; then
@@ -579,7 +647,7 @@ _almonwatch () {
 				else
 					echo "Whitelist override: false"
 					osaprompt="The application '$appname' with the Bundle ID '$bundleid' has the following issues:"
-					_beep
+					_beep &
 					_notify "⚠️ There are issues!" "$appname"
 					userchoice=$(_prompt "$osaprompt" "$osaissue")
 					if [[ $userchoice == "Whitelist" ]] ; then
@@ -603,7 +671,7 @@ _almonwatch () {
 					else
 						_whitelist remove
 						echo "Aborting launch: $appname"
-						osascript -e 'tell application "$appname" to quit' && { sleep .5 ; kill -s KILL $pid 2>/dev/null ; }
+						osascript -e 'tell application "$appname" to quit' && { sleep 3 ; kill -s KILL $pid 2>/dev/null ; }
 						if ! $hashchange ; then
 							bash -c '"$supportdir"/bin/run "$notification:::0:::samehash"' 2>/dev/null &
 						else
