almonwatch v1.0 b5
support for java check, if user launches a .jar file

diff --git a/almonwatch b/almonwatch
--- a/almonwatch
+++ b/almonwatch
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # almonwatch
-# version 1.0 beta 4 rev 3
+# version 1.0 beta 5
 
 # set -x
 # PS4=':$LINENO+'
@@ -461,6 +461,9 @@ _almonwatch () {
 			break
 
 		else
+
+			echo -e "\n*** Launch detected ***"
+
 			# blank settings
 			errors=false
 			unsigned=false
@@ -475,19 +478,44 @@ _almonwatch () {
 
 			# parse input
 			pid=$(echo "$notification" | awk -F":::" '{print $2}')
-			filepath=$(echo "$notification" | awk -F":::" '{print $3}')
-			[[ -h "$filepath" ]] && filepath=$(perl -MCwd -e 'print Cwd::abs_path shift' "$filepath")
 			appname=$(echo "$notification" | awk -F":::" '{print $5}')
 			bundleid=$(echo "$notification" | awk -F":::" '{print $4}')
-			plistloc="$filepath/Contents/Info.plist"
 			nsworkspace=$(echo "$notification" | awk -F":::" '{print $1}')
+			nsworkspace2=$(echo "$notification" | awk -F":::" '{print substr($0, index($0,$3))}')
 
-			# determine executable
-			executable=$(plutil -p "$plistloc" | awk -F\" '/CFBundleExecutable/{print $4}')
-			exepath="$filepath/Contents/MacOS/$executable"
+			# parse for filepath & check
+			filepath=$(echo "$notification" | awk -F":::" '{print $3}')
+			filename=$(basename "$filepath")
+			[[ -h "$filepath" ]] && filepath=$(perl -MCwd -e 'print Cwd::abs_path shift' "$filepath")
+			mdls_output=$(mdls -name kMDItemContentTypeTree "$filepath")
+			if ! [[ -d "$filepath" ]] || ! [[ $(echo "$mdls_output" | grep "\"com.apple.package\",") ]] ; then
+				filelaunch=true
+				echo "$filename: error - no com.apple.package"
+				if [[ $(echo "$mdls_output" | grep "\"public.executable\",") ]] ; then
+					echo "Executable launched: $filepath"
+				else
+					echo "Other file launched: $filepath"
+				fi
+				executable="$filename"
+				exepath="$filepath"
+				originalname="$appname"
+				appname="$filename"
+			else
+				filelaunch=false
+				echo "$filename: com.apple.package"
+				# determine executable (package)
+				plistloc="$filepath/Contents/Info.plist"
+				executable=$(plutil -p "$plistloc" | awk -F\" '/CFBundleExecutable/{print $4}')
+				exepath="$filepath/Contents/MacOS/$executable"
+
+			fi
 
 			# initial log
-			echo -e "\n*** Launch detected ***\nName: $appname\nBundle ID: $bundleid\nPath: $filepath\nProcess ID: $pid\nExecutable: $exepath\nNSWorkspace: $nsworkspace"
+			if ! $filelaunch ; then
+				echo -e "Name: $appname\nBundle ID: $bundleid\nPath: $filepath\nProcess ID: $pid\nExecutable: $exepath\nNSWorkspace: $nsworkspace\nNSWorkspace: $nsworkspace2"
+			else
+				echo -e "Original name: $originalname\nName: $appname\nBundle ID: $bundleid\nPath: $filepath\nProcess ID: $pid\nExecutable: $exepath\nNSWorkspace: $nsworkspace\nNSWorkspace: $nsworkspace2"
+			fi
 
 			# check whitelist status
 			wlstatus=$(sqlite3 "$dbloc" "select whitelist from ALM where cfbid=\"$bundleid\";" 2>/dev/null)
